# Generated by Django 4.2.3 on 2023-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='icone',
            field=models.ImageField(upload_to='icone'),
        ),
    ]
